name: Format

on:
    push:
        branches: [main]
    pull_request:
    workflow_dispatch:

jobs:
    check-format:
        runs-on: ubuntu-latest
        permissions:
            checks: write
            issues: write
            pull-requests: write
        steps:
            - uses: actions/checkout@v5
              with:
                  fetch-depth: 0
            - uses: pre-commit/action@v3.0.1
            - if: ${{ github.event_name == 'pull_request' && failure() }}
              uses: reviewdog/action-suggester@v1
              with:
                  tool_name: pre-commit
                  cleanup: false
